### ISSUE TITLE
Support for openai > 1.0.0

### ISSUE THREAD

**Issue by paulpierre** [pezzolabs/client-python#2]
Please update support for this breaking change. Last update was 2 months ago.

**Comment by arielweinberger** [comment]
@paulpierre We just launched Pezzo Proxy which natively supports OpenAI across all languages. You can learn more about it [here](https://docs.pezzo.ai/platform/proxy/overview) and find a detailed Python integration tutorial [here](https://docs.pezzo.ai/introduction/tutorial-observability/overview).

This repo will now be archived.
